### ISSUE TITLE
Attempt to access "3D Scene" repeatedly crashes viewer!

### ISSUE THREAD

**Issue by zoldos** [cinderblocks/radegast#32]
I'm running the latest release of the viewer (clean install).  It loads up and logs on perfectly.  However, all attempts at using "3D Scene" result in the viewer's crash.  I'm on Windows 10 64 bit and an Nvidia Geforce GTX 960 graphics with 4GB vram and 32GB system ram.

**Comment by jmfergeau** [comment]
Same. Systematic crash on 3D scene. with the exact same GPU and VRAM. Except i'm on Arch linux with LTS kernel and not windows.

**Comment by Wolphin5** [comment]
I have seen that too on my system over the years... I will get 1 3D view (Scene or object) for sure... but beyond that, each one I open is more likely to crash Radegast, and usually needs to reboot the computer before it will work again.
Windows 10 Pro, with latest updated
AMD AM4 3600X, ASUS Crosshair VIII Hero Wifi MB, 32 GB 3200 MHz RAM, Asus TUF Gaming GeForce RTX 3080 Ti (Also had it before I upgraded, on a GeForce GTX 1080 FTW2)

**Comment by DonaldAlan** [comment]
I see the cause in ~/AppData/Roaming/Radegast/Radegast.log:

```
14:43:17 [ERROR] - Crash of the 3D scene viewer:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Radegast.Rendering.RenderPrimitive.Render(RenderPass pass, Int32 pickingID, SceneWindow scene, Single time) in C:\projects\radegast\Radegast\GUI\Rendering\RenderPrimitive.cs:line 429
   at Radegast.Rendering.SceneWindow.RenderObjects(RenderPass pass) in C:\projects\radegast\Radegast\GUI\Rendering\Rendering.cs:line 2355
   at Radegast.Rendering.SceneWindow.Render(Boolean picking) in C:\projects\radegast\Radegast\GUI\Rendering\Rendering.cs:line 2495
   at Radegast.Rendering.SceneWindow.MainRenderLoop() in C:\projects\radegast\Radegast\GUI\Rendering\Rendering.cs:line 812
   at Radegast.Rendering.SceneWindow.Application_Idle(Object sender, EventArgs e) in C:\projects\radegast\Radegast\GUI\Rendering\Rendering.cs:line 309
```
I'm using version RadegastSetup_x86-2.41.357.exe on Windows 11 Pro, with plenty of memory and an NVIDIA GeForce RTX 4070 Ti.

**Comment by cinderblocks** [comment]
Can you give me a location inworld? If not here, to my e-mail address or Cinder Roxley in Second Life.

**Comment by DonaldAlan** [comment]
I'm Alan Ramona in SL. I IMed you in SL but you weren't logged in.

**Comment by vharr** [comment]
> Can you give me a location inworld? If not here, to my e-mail address or Cinder Roxley in Second Life.

It reliably crashes at Welcome Hub: https://maps.secondlife.com/secondlife/WelcomeHub/128/128/2

**Comment by PeterBBCUser** [comment]
just updated to latest version 2.45.399.0 running it on windows 10 and it flashes up a big red X on the screen but displays nothing any more for the 3D Scene, and does not seem to make any difference what Graphics option I turn on or off, some times it still crashes Radegast.

**Comment by cinderblocks** [comment]
This particular crash resolved in bae97e8885dc7318810dd7fbccc7a94ac8251874. Should be in next release. Related to #69
